backend:
  name: local

collections:
  - name: "projects"
    label: "Projects"
    folder: "_data"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"} 