backend:
  name: local

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Portfolio Projects"
    folder: "_data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image URL", name: "imageUrl", widget: "string"}
      - {label: "Medium", name: "medium", widget: "select", options: ["code", "art", "writing"]}
      - {label: "Genres", name: "genre", widget: "list", field: {label: "Genre", name: "genre", widget: "string"}}
      - {label: "Styles/Themes", name: "style", widget: "list", field: {label: "Style", name: "style", widget: "string"}}
      - {label: "Technologies", name: "tech", widget: "list", field: {label: "Technology", name: "tech", widget: "string"}}
      - {label: "Mood", name: "mood", widget: "string"}
      - {label: "Year", name: "year", widget: "number", value_type: "int"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Links", name: "links", widget: "object", fields: [
          {label: "Live Site", name: "live", widget: "string", required: false},
          {label: "GitHub", name: "github", widget: "string", required: false},
          {label: "Demo", name: "demo", widget: "string", required: false}
        ]}
      - {label: "Pitch", name: "pitch", widget: "text"}
      - {label: "Challenge", name: "challenge", widget: "text"}
      - {label: "Development", name: "development", widget: "text"}
      - {label: "Outcome", name: "outcome", widget: "text"}

  - name: "site-settings"
    label: "Site Settings"
    files:
      - file: "_data/site-settings.json"
        label: "Site Configuration"
        name: "site-settings"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "About Text", name: "about", widget: "markdown"}
          - {label: "Social Links", name: "social", widget: "object", fields: [
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
              {label: "GitHub", name: "github", widget: "string", required: false},
              {label: "Twitter", name: "twitter", widget: "string", required: false},
              {label: "Portfolio", name: "portfolio", widget: "string", required: false}
            ]}

  - name: "categories"
    label: "Categories"
    files:
      - file: "_data/categories.json"
        label: "Filter Categories"
        name: "categories"
        fields:
          - {label: "Genres", name: "genres", widget: "list", field: {label: "Genre", name: "genre", widget: "string"}}
          - {label: "Styles", name: "styles", widget: "list", field: {label: "Style", name: "style", widget: "string"}}
          - {label: "Technologies", name: "technologies", widget: "list", field: {label: "Technology", name: "tech", widget: "string"}}
          - {label: "Moods", name: "moods", widget: "list", field: {label: "Mood", name: "mood", widget: "string"}} 